[package]
name = "jampack"
version = "0.0.1"
edition = "2021"
authors = ["WrapFX"]
description = "Asynchronous, extensible asset pipeline for games and apps"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/WrapFX/jampack"

[dependencies]
log = "0.4.17"
pollster = { version = "0.2.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm-bindgen = "0.2.83"
#wasm-bindgen-futures = "0.4.33"
#console_error_panic_hook = "0.1.7"
#console_log = "0.2.0"
gloo-net = "0.2.4"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []